#!/bin/bash
#SBATCH --job-name=L8_e0.5_h5.4_bmin0.2_bmax0.25          # Name of the job
#SBATCH --time=7-00:00:00               # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=1               # Number of nodes
#SBATCH --ntasks=32
#SBATCH --output=/home/cluster_users/x_ilaria/MultiComponents_SC/Output_2C/L8_e0.5_h5.4_bmin0.2_bmax0.25/logs/log_L8_e0.5_h5.4_bmin0.2_bmax0.25.o
#SBATCH --error=/home/cluster_users/x_ilaria/MultiComponents_SC/Output_2C/L8_e0.5_h5.4_bmin0.2_bmax0.25/logs/log_L8_e0.5_h5.4_bmin0.2_bmax0.25.e


srun ../build/Release/GL_2component 8 /home/cluster_users/x_ilaria/MultiComponents_SC/Output_2C/L8_e0.5_h5.4_bmin0.2_bmax0.25 &> /home/cluster_users/x_ilaria/MultiComponents_SC/Output_2C/L8_e0.5_h5.4_bmin0.2_bmax0.25/logs/log_L8_e0.5_h5.4_bmin0.2_bmax0.25.o



